In [1]:
import pandas as pd

In [6]:
df = pd.read_excel('data/dataset_exercices.xlsx')
df

,client_id,prenom,nom,age,pays,ville,statut,categorie,date_commande,quantite,prix_unitaire,total_achat,note_satisfaction
0,C1000,Laura,Bernard,33,France,Bordeaux,Standard,Alimentation,2023-02-22,9,47.95,431.55,4
1,C1001,Thomas,Martin,32,France,Toulouse,Standard,Électronique,2023-10-15,4,358.71,1434.84,5
2,C1002,Pierre,Simon,35,Maroc,Marrakech,Premium,Alimentation,2023-12-24,7,173.08,1211.56,2
3,C1003,Sophie,Rousseau,42,France,Lyon,Standard,Beauté,2023-06-26,10,135.67,1356.70,1
4,C1004,Maxime,Morel,42,Belgique,Bruxelles,Standard,Sport,2023-11-18,10,442.41,4424.10,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,C1195,Amina,Rousseau,47,Canada,Ottawa,Standard,Alimentation,2023-06-17,10,162.35,1623.50,4
196,C1196,Théo,Garcia,50,Espagne,Barcelone,Standard,Jeux vidéo,2023-12-29,10,153.10,1531.00,1
197,C1197,Hugo,Rousseau,55,France,Lille,VIP,Électronique,2023-11-02,8,136.17,1089.36,5
198,C1198,Inès,Simon,28,France,Strasbourg,Standard,Livres,2023-03-17,4,20.60,82.40,1
199,C1199,Sophie,Martin,44,Maroc,Rabat,Standard,Livres,2023-12-20,4,207.73,830.92,5

In [ ]:
#Exo 1 - Filtre les clients avec une note de satisfaction de 5. 👀
df[df['note_satisfaction'] == 5].head(10)

,client_id,prenom,nom,age,pays,ville,statut,categorie,date_commande,quantite,prix_unitaire,total_achat,note_satisfaction
1,C1001,Thomas,Martin,32,France,Toulouse,Standard,Électronique,2023-10-15,4,358.71,1434.84,5
8,C1008,Manon,Dupont,69,Belgique,Bruxelles,Standard,Livres,2023-05-18,2,109.23,218.46,5
9,C1009,Sara,Rousseau,43,Belgique,Anvers,Premium,Alimentation,2023-05-16,3,126.83,380.49,5
11,C1011,Elisa,Dupont,58,France,Marseille,Standard,Livres,2023-11-02,2,195.08,390.16,5
13,C1013,Ahmed,Morel,50,France,Bordeaux,Standard,Vêtements,2023-11-17,5,420.78,2103.90,5
15,C1015,Axel,Blanc,21,Espagne,Madrid,Standard,Vêtements,2023-02-13,8,408.12,3264.96,5
19,C1019,Baptiste,Rousseau,35,France,Toulouse,Premium,Maison,2023-10-04,3,362.34,1087.02,5
25,C1025,Rayan,Chevalier,27,Belgique,Anvers,Standard,Sport,2023-04-22,1,291.12,291.12,5
40,C1040,Kevin,Durand,25,Italie,Rome,VIP,Alimentation,2023-10-25,5,23.90,119.50,5
44,C1044,Pierre,Girard,43,France,Bordeaux,Standard,Électronique,2023-06-05,5,108.83,544.15,5

In [ ]:
#Exo 2 - Même chose mais cette fois groupe par statut et compte combien y'en a dans chaque groupe. 👀
df[df['note_satisfaction'] == 5].groupby('statut').size()

statut
Premium     10
Standard    27
VIP          4
dtype: int64

In [ ]:
#Exo 3 - Calcule la moyenne de total_achat par catégorie, et garde seulement celles au-dessus de la moyenne globale. 👀

mean_achat_by_cat = df.groupby('categorie')['total_achat'].mean()
mean_achat = df['total_achat'].mean()
mean_achat
mean_achat_by_cat[mean_achat_by_cat > mean_achat]

categorie
Beauté          1698.723462
Maison          1709.656500
Sport           1446.752917
Vêtements       1397.366667
Électronique    1510.856538
Name: total_achat, dtype: float64

In [ ]:
#Exo 3 corrigé - En plus rapide :
mean_achat_by_cat = df.groupby('categorie')['total_achat'].mean()
mean_achat_by_cat[mean_achat_by_cat > mean_achat_by_cat.mean()]