In [17]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('data/dataset_exercices.xlsx')
df

,client_id,prenom,nom,age,pays,ville,statut,categorie,date_commande,quantite,prix_unitaire,total_achat,note_satisfaction
0,C1000,Laura,Bernard,33,France,Bordeaux,Standard,Alimentation,2023-02-22,9,47.95,431.55,4
1,C1001,Thomas,Martin,32,France,Toulouse,Standard,Électronique,2023-10-15,4,358.71,1434.84,5
2,C1002,Pierre,Simon,35,Maroc,Marrakech,Premium,Alimentation,2023-12-24,7,173.08,1211.56,2
3,C1003,Sophie,Rousseau,42,France,Lyon,Standard,Beauté,2023-06-26,10,135.67,1356.70,1
4,C1004,Maxime,Morel,42,Belgique,Bruxelles,Standard,Sport,2023-11-18,10,442.41,4424.10,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,C1195,Amina,Rousseau,47,Canada,Ottawa,Standard,Alimentation,2023-06-17,10,162.35,1623.50,4
196,C1196,Théo,Garcia,50,Espagne,Barcelone,Standard,Jeux vidéo,2023-12-29,10,153.10,1531.00,1
197,C1197,Hugo,Rousseau,55,France,Lille,VIP,Électronique,2023-11-02,8,136.17,1089.36,5
198,C1198,Inès,Simon,28,France,Strasbourg,Standard,Livres,2023-03-17,4,20.60,82.40,1
199,C1199,Sophie,Martin,44,Maroc,Rabat,Standard,Livres,2023-12-20,4,207.73,830.92,5

In [3]:
#Exo 1 - Filtre les clients avec une note de satisfaction de 5. 👀
df[df['note_satisfaction'] == 5].head(10)

,client_id,prenom,nom,age,pays,ville,statut,categorie,date_commande,quantite,prix_unitaire,total_achat,note_satisfaction
1,C1001,Thomas,Martin,32,France,Toulouse,Standard,Électronique,2023-10-15,4,358.71,1434.84,5
8,C1008,Manon,Dupont,69,Belgique,Bruxelles,Standard,Livres,2023-05-18,2,109.23,218.46,5
9,C1009,Sara,Rousseau,43,Belgique,Anvers,Premium,Alimentation,2023-05-16,3,126.83,380.49,5
11,C1011,Elisa,Dupont,58,France,Marseille,Standard,Livres,2023-11-02,2,195.08,390.16,5
13,C1013,Ahmed,Morel,50,France,Bordeaux,Standard,Vêtements,2023-11-17,5,420.78,2103.90,5
15,C1015,Axel,Blanc,21,Espagne,Madrid,Standard,Vêtements,2023-02-13,8,408.12,3264.96,5
19,C1019,Baptiste,Rousseau,35,France,Toulouse,Premium,Maison,2023-10-04,3,362.34,1087.02,5
25,C1025,Rayan,Chevalier,27,Belgique,Anvers,Standard,Sport,2023-04-22,1,291.12,291.12,5
40,C1040,Kevin,Durand,25,Italie,Rome,VIP,Alimentation,2023-10-25,5,23.90,119.50,5
44,C1044,Pierre,Girard,43,France,Bordeaux,Standard,Électronique,2023-06-05,5,108.83,544.15,5

In [4]:
#Exo 2 - Même chose mais cette fois groupe par statut et compte combien y'en a dans chaque groupe. 👀
df[df['note_satisfaction'] == 5].groupby('statut').size()

statut
Premium     10
Standard    27
VIP          4
dtype: int64

In [5]:
#Exo 3 - Calcule la moyenne de total_achat par catégorie, et garde seulement celles au-dessus de la moyenne globale. 👀

mean_achat_by_cat = df.groupby('categorie')['total_achat'].mean()
mean_achat = df['total_achat'].mean()
mean_achat
mean_achat_by_cat[mean_achat_by_cat > mean_achat]

categorie
Beauté          1698.723462
Maison          1709.656500
Sport           1446.752917
Vêtements       1397.366667
Électronique    1510.856538
Name: total_achat, dtype: float64

In [6]:
#Exo 3 corrigé - En plus rapide :
mean_achat_by_cat = df.groupby('categorie')['total_achat'].mean()
mean_achat_by_cat[mean_achat_by_cat > mean_achat_by_cat.mean()]

categorie
Beauté          1698.723462
Maison          1709.656500
Sport           1446.752917
Électronique    1510.856538
Name: total_achat, dtype: float64

In [7]:
#Exo 1.1 -  Crée une colonne mois et donne le CA total par mois. 👀
df['month'] = df['date_commande'].dt.month
df.groupby('month')['total_achat'].sum()

month
1      5628.35
2     29336.46
3     25883.03
4     11037.13
5     28500.69
6     20771.48
7     25472.73
8     31011.88
9     13605.69
10    19228.21
11    30848.00
12    38048.22
Name: total_achat, dtype: float64

In [8]:
#Exo 1.2 - Pour chaque ville, donne le nombre de clients distincts et leur dépense moyenne. 👀

summary_df = df.groupby('ville').agg(
    unique_client=('client_id', 'nunique'),
    mean_spending=('total_achat', 'mean')
).round(2)

In [9]:
summary_df['mean_spending'] = summary_df['mean_spending'].astype(str) + ' €'
summary_df

            unique_client mean_spending
ville
Anvers                  9      962.29 €
Barcelone              14     1390.58 €
Berlin                  3     1099.01 €
Bordeaux               10     1132.58 €
Bruxelles               5     1306.59 €
Casablanca              4     1279.95 €
Florence                4     2184.93 €
Gand                    6      483.56 €
Genève                  5     1442.74 €
Hambourg                4      672.74 €
Lausanne                2      595.89 €
Lille                  12     1368.94 €
Liège                   8     1794.39 €
Lyon                   13     1737.64 €
Madrid                  9     1833.03 €
Marrakech               4     2269.17 €
Marseille               9     2185.93 €
Milan                   1       989.0 €
Montréal                1      690.36 €
Nantes                  9     1603.19 €
Ottawa                  4      769.87 €
Paris                  13     1411.81 €
Québec                  1     2206.14 €
Rabat                   8     1923.08 €
Rome                    3      854.69 €
Strasbourg             15     1600.72 €
Séville                10     1254.19 €
Toulouse               11      692.78 €
Zurich                  3      580.62 €

In [10]:
#Exo 1.3 - Identifie les villes avec une dépense moyenne au-dessus de la médiane globale de total_achat. 👀

med_city_above_average = df.groupby('ville')['total_achat'].mean()
med_city_above_average = med_city_above_average[med_city_above_average > df['total_achat'].median()]
med_city_above_average

ville
Barcelone     1390.580000
Bruxelles     1306.592000
Casablanca    1279.952500
Florence      2184.932500
Genève        1442.736000
Lille         1368.941667
Liège         1794.388750
Lyon          1737.635385
Madrid        1833.034444
Marrakech     2269.172500
Marseille     2185.932222
Nantes        1603.191111
Paris         1411.812308
Québec        2206.140000
Rabat         1923.082500
Strasbourg    1600.716000
Séville       1254.190000
Name: total_achat, dtype: float64

In [11]:
df['total_achat'].median()

1151.39

In [12]:
df.head()

,client_id,prenom,nom,age,pays,ville,statut,categorie,date_commande,quantite,prix_unitaire,total_achat,note_satisfaction,month
0,C1000,Laura,Bernard,33,France,Bordeaux,Standard,Alimentation,2023-02-22,9,47.95,431.55,4,2
1,C1001,Thomas,Martin,32,France,Toulouse,Standard,Électronique,2023-10-15,4,358.71,1434.84,5,10
2,C1002,Pierre,Simon,35,Maroc,Marrakech,Premium,Alimentation,2023-12-24,7,173.08,1211.56,2,12
3,C1003,Sophie,Rousseau,42,France,Lyon,Standard,Beauté,2023-06-26,10,135.67,1356.70,1,6
4,C1004,Maxime,Morel,42,Belgique,Bruxelles,Standard,Sport,2023-11-18,10,442.41,4424.10,3,11

In [13]:
#Exo 2.1 - Donne le mois avec le plus fort taux de clients VIP (en % du total des commandes de ce mois). 👀

vip = df[df['statut'] == 'VIP'].groupby('month')['quantite'].count()
vip_percent_by_month = (vip / df.groupby('month')['quantite'].count() * 100).round(2)
vip_percent_by_month.nlargest(1)

month
3    22.22
Name: quantite, dtype: float64

In [14]:
#Exo 2.2 - Donne la répartition des notes de satisfaction par statut en %. 👀


satisfaction = df.groupby(['statut', 'note_satisfaction']).size()
satisfaction
rating_by_status = satisfaction / satisfaction.groupby('statut').transform('sum') * 100
rating_by_status.round(2)

statut    note_satisfaction
Premium   1                    21.28
          2                    21.28
          3                    21.28
          4                    14.89
          5                    21.28
Standard  1                    27.41
          2                    16.30
          3                    18.52
          4                    17.78
          5                    20.00
VIP       1                    11.11
          2                    11.11
          3                    22.22
          4                    33.33
          5                    22.22
dtype: float64

In [15]:
df.head()

,client_id,prenom,nom,age,pays,ville,statut,categorie,date_commande,quantite,prix_unitaire,total_achat,note_satisfaction,month
0,C1000,Laura,Bernard,33,France,Bordeaux,Standard,Alimentation,2023-02-22,9,47.95,431.55,4,2
1,C1001,Thomas,Martin,32,France,Toulouse,Standard,Électronique,2023-10-15,4,358.71,1434.84,5,10
2,C1002,Pierre,Simon,35,Maroc,Marrakech,Premium,Alimentation,2023-12-24,7,173.08,1211.56,2,12
3,C1003,Sophie,Rousseau,42,France,Lyon,Standard,Beauté,2023-06-26,10,135.67,1356.70,1,6
4,C1004,Maxime,Morel,42,Belgique,Bruxelles,Standard,Sport,2023-11-18,10,442.41,4424.10,3,11

In [ ]:
#Exo 3.1 - Donne la corrélation entre age et total_achat — et interprète le résultat. 👀

df[['age', 'total_achat']].corr()

                  age  total_achat
age          1.000000    -0.062154
total_achat -0.062154     1.000000

In [ ]:
conditions = [(df['age']>18) & (df['age']<=29), 
              (df['age']>29) & (df['age']<=39),
              (df['age']>39) & (df['age']<=49), 
              (df['age']>49)]


choices = ['Faible', 'Moyen', 'Élevé']

In [20]:
#Exo 3.2 - Crée une colonne decennie qui regroupe les ages par tranche : 18-29, 30-39, 40-49, 50+. Ensuite donne la dépense moyenne par tranche. 👀


df['decennie'] = pd.cut(
    df['age'],
    bins=[18, 29, 39, 49, float('inf')],
    labels=['18-29', '30-39', '40-49', '50+']
)
df.groupby('decennie')['total_achat'].mean()

decennie
18-29    1283.620000
30-39    1505.070857
40-49    1600.614146
50+      1286.195244
Name: total_achat, dtype: float64

In [27]:
#Exo 3.3 - Parmi les clients de 50+, quels pays ont une dépense médiane supérieure à la médiane globale de ce groupe ? 👀

filtre = df[df['decennie'] == '50+'].groupby('pays')['total_achat'].median()
pays_seniors_high_spend = filtre[filtre > df[df['decennie'] == '50+']['total_achat'].median()
]
pays_seniors_high_spend

pays
Espagne    1042.02
France     1152.24
Italie     1233.76
Maroc      2009.46
Name: total_achat, dtype: float64

In [23]:
df[df['decennie'] == '50+']['total_achat'].median()

996.38

In [28]:
#Exo 3.4 - Applique un rank() sur total_achat par pays — du plus dépensier au moins — et affiche les clients qui sont #1 dans leur pays. 👀

df['rank_in_pays'] = df.groupby('pays')['total_achat'].rank(ascending=False, method='dense')
df[df['rank_in_pays'] == 1][['client_id', 'pays', 'total_achat', 'rank_in_pays']]

    client_id       pays  total_achat  rank_in_pays
6       C1006  Allemagne      1758.50           1.0
29      C1029      Maroc      4982.40           1.0
90      C1090     France      3913.92           1.0
92      C1092     Suisse      2168.48           1.0
106     C1106     Italie      3941.73           1.0
133     C1133    Espagne      3439.24           1.0
154     C1154   Belgique      4913.10           1.0
186     C1186     Canada      2206.14           1.0