In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_excel('data/dataset_exercices.xlsx', sheet_name='commandes')

In [5]:
df.head()

,client_id,prenom,nom,age,pays,ville,statut,categorie,date_commande,quantite,prix_unitaire,total_achat,note_satisfaction
0,C1000,Laura,Bernard,33,France,Bordeaux,Standard,Alimentation,2023-02-22,9,47.95,431.55,4
1,C1001,Thomas,Martin,32,France,Toulouse,Standard,Électronique,2023-10-15,4,358.71,1434.84,5
2,C1002,Pierre,Simon,35,Maroc,Marrakech,Premium,Alimentation,2023-12-24,7,173.08,1211.56,2
3,C1003,Sophie,Rousseau,42,France,Lyon,Standard,Beauté,2023-06-26,10,135.67,1356.70,1
4,C1004,Maxime,Morel,42,Belgique,Bruxelles,Standard,Sport,2023-11-18,10,442.41,4424.10,3

In [6]:
df_french_touch = df[df['pays']=='France']

In [7]:
#1er essai brouillon
df[df['pays']=='France'].groupby('pays')['total_achat'].mean()

pays
France    1461.188043
Name: total_achat, dtype: float64

In [8]:
df_french_touch['total_achat'].mean()

1461.1880434782609

In [9]:
df.groupby('pays')['total_achat'].mean()

pays
Allemagne     855.424286
Belgique     1158.929286
Canada        995.995000
Espagne      1469.919091
France       1461.188043
Italie       1536.601250
Maroc        1848.822500
Suisse       1014.731000
Name: total_achat, dtype: float64

In [10]:
df['pays'].unique()

<ArrowStringArray>
[   'France',     'Maroc',  'Belgique', 'Allemagne',   'Espagne',    'Suisse',
    'Italie',    'Canada']
Length: 8, dtype: str

In [11]:
summary_df = df.groupby('pays').agg(
    sum_total_achat=('total_achat', 'sum'),
    avg_satisfaction=('note_satisfaction', 'mean')
).reset_index().round(2)

summary_df

        pays  sum_total_achat  avg_satisfaction
0  Allemagne          5987.97              2.43
1   Belgique         32450.02              3.21
2     Canada          5975.97              3.33
3    Espagne         48507.33              2.70
4     France        134429.30              2.90
5     Italie         12292.81              3.12
6      Maroc         29581.16              2.81
7     Suisse         10147.31              3.40

In [ ]:
df.groupby('categorie')['total_achat'].sum().sort_values(ascending=False).head(3)
# ou df.groupby('categorie')['total_achat'].sum().nlargest(3)

categorie
Beauté          44166.81
Vêtements       41921.00
Électronique    39282.27
Name: total_achat, dtype: float64

In [18]:
df[df['statut'] == 'Premium'].groupby('pays')['total_achat'].mean().round(2)

pays
Belgique    1557.39
Canada       300.70
Espagne     1927.62
France      1491.66
Maroc       1546.84
Suisse      1175.42
Name: total_achat, dtype: float64

In [19]:
df['total_achat'].describe()

count     200.000000
mean     1396.859350
std      1096.476481
min        27.380000
25%       505.132500
50%      1151.390000
75%      1947.120000
max      4982.400000
Name: total_achat, dtype: float64

In [24]:
df.nlargest(5, 'total_achat')[['pays', 'categorie', 'total_achat']]

         pays     categorie  total_achat
29      Maroc  Électronique      4982.40
154  Belgique        Maison      4913.10
4    Belgique         Sport      4424.10
49      Maroc        Beauté      4076.10
106    Italie        Maison      3941.73

In [25]:
df['montant_tva'] = df['total_achat'] * 0.2
df.head()

,client_id,prenom,nom,age,pays,ville,statut,categorie,date_commande,quantite,prix_unitaire,total_achat,note_satisfaction,montant_tva
0,C1000,Laura,Bernard,33,France,Bordeaux,Standard,Alimentation,2023-02-22,9,47.95,431.55,4,86.310
1,C1001,Thomas,Martin,32,France,Toulouse,Standard,Électronique,2023-10-15,4,358.71,1434.84,5,286.968
2,C1002,Pierre,Simon,35,Maroc,Marrakech,Premium,Alimentation,2023-12-24,7,173.08,1211.56,2,242.312
3,C1003,Sophie,Rousseau,42,France,Lyon,Standard,Beauté,2023-06-26,10,135.67,1356.70,1,271.340
4,C1004,Maxime,Morel,42,Belgique,Bruxelles,Standard,Sport,2023-11-18,10,442.41,4424.10,3,884.820